### ISSUE TITLE
running on windows w/ Python ?

### ISSUE THREAD

**Issue by tomergilad** [sraorao/AnimApp#9]
Hello, and thank you for sharing your work.

 I'd like to run AnimApp for my research (learning and forgetting in ants) and some other projects in our lab.  I  only have access to Windows-based machines and we usually work in R studio.

is it possible to run AnimApp with a Python desktop Environment installed on Windows ? 
And if so, which libraries/dependencies  do I need ?

thank you in advance for you advice and time.

Tomer.

**Comment by sraorao** [comment]
Hi Tomer,

We currently don't have instructions written down for a Windows system. The main reason is that the installation of dependencies is a bit more complicated and we haven't done a complete installation and testing on a Windows system to work out any issues. But in theory, it should work as long as the following dependencies are also installed:
- python 2.7
- opencv 3.2 (importantly, this installation must include ffmpeg support for video analysis to work. From memory, this involved installing ffmpeg, and then copying a .dll file into the opencv installation directory, as described here: http://techspirityou.blogspot.com/2016/04/guide-to-installing-opencvpython-setup.html although these instructions are for an older version)
- numpy, pandas packages in python

Alternatively, if you have access to a machine running Ubuntu (you can easily install Ubuntu as a dual-boot parallel to your existing Windows), or a Mac, you can follow the instructions here: https://github.com/sraorao/animapp_desktop

Hope this helps, please let me know if you encounter any issues.

Rao

**Comment by sraorao** [comment]
Hi @tomergilad ,

I have now updated the desktop version of Animapp, which works on Windows too, please give that a try if you are still looking. Installation instructions are here: https://animapp.readthedocs.io/en/latest/ 

I'm closing this now, but feel free to open another issue in the https://github.com/sraorao/animapp_conda repo if you have any questions regarding the new repo.

BW
Rao
